# Generated by Django 3.1.1 on 2020-09-24 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Вопрос')),
                ('description', models.TextField(verbose_name='Текст вопроса')),
                ('type', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Опрос')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Опроы',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Ответ')),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveyusers.questions')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveyusers.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveyusers.user')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
